# Docker in Docker for Jenkins
# RUN THIS IMAGE IF YOU DON'T HAVE JENKINS SLAVE. THIS WILL CREATE A USER 1000, WHICH IS WHAT JENKINS USER ID IS
# SO IT WON'T CONFLICT WITH JENKINS LOCAL DIRECTORY PERMISSIONS

FROM alpine:3.12.4

LABEL name="viejo/dind4jenkins:alpine_3_12_master"

LABEL description="Docker in Docker on alpine:3.12 with AWS cli v2 and Google Cloud SDK"

ENV CLOUD_SDK_VERSION=286.0.0 \
    CLOUDSDK_PYTHON=python3 \
    PATH=/google-cloud-sdk/bin:$PATH
    
RUN adduser --disabled-password -u 1000 -G ping -s /bin/sh jenkins

# AWS-CLI & GCLOUD
RUN apk -v --update add \
        bash \
        docker \
        python3 \
        py3-pip \
        curl \
        py3-crcmod \
        libc6-compat \
        openssh-client \
        git \
        gnupg \
        jq \
        gawk \
        npm
        
RUN  pip3 install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic \
        && pip3 install --upgrade awscli \
        && apk -v --purge del py-pip \
        && rm /var/cache/apk/* \
        && curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz \
        && tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz \
        && rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz \
        && gcloud config set core/disable_usage_reporting true \
        && gcloud config set component_manager/disable_update_check true \
        && gcloud config set metrics/environment github_docker_image \
        && gcloud --version